-- Table des rôles
CREATE TABLE roles (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(50) NOT NULL UNIQUE
);

-- Table des utilisateurs
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(200) NOT NULL,
    role_id NUMBER NOT NULL,
    created_at DATE DEFAULT SYSDATE,

    CONSTRAINT fk_role
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id)
);

-- Table des cours
CREATE TABLE courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    description CLOB,
    created_by NUMBER NOT NULL,

    CONSTRAINT fk_creator
        FOREIGN KEY (created_by)
        REFERENCES users(user_id)
);

-- Table des chapitres
CREATE TABLE chapters (
    chapter_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    content CLOB,

    CONSTRAINT fk_course
        FOREIGN KEY (course_id)
        REFERENCES courses(course_id)
);
CREATE TABLE quizzes (
    quiz_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id NUMBER NOT NULL,
    title VARCHAR2(200) NOT NULL,
    description CLOB,
    passing_score NUMBER(5,2) DEFAULT 100 NOT NULL,

    CONSTRAINT fk_quiz_chapter
        FOREIGN KEY (chapter_id)
        REFERENCES chapters(chapter_id)
);
CREATE TABLE questions (
    question_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id NUMBER NOT NULL,
    question_text CLOB NOT NULL,
    question_type VARCHAR2(50) DEFAULT 'QCM' NOT NULL,
    points NUMBER DEFAULT 1 NOT NULL,

    CONSTRAINT fk_question_quiz
        FOREIGN KEY (quiz_id)
        REFERENCES quizzes(quiz_id)
);
CREATE TABLE choices (
    choice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id NUMBER NOT NULL,
    choice_text VARCHAR2(500) NOT NULL,
    is_correct NUMBER(1) DEFAULT 0 NOT NULL
        CHECK (is_correct IN (0,1)),

    CONSTRAINT fk_choice_question
        FOREIGN KEY (question_id)
        REFERENCES questions(question_id)
);
CREATE TABLE quiz_attempts (
    attempt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    score NUMBER(5,2),
    passed NUMBER(1) DEFAULT 0 NOT NULL
        CHECK (passed IN (0,1)),
    attempt_date DATE DEFAULT SYSDATE,

    CONSTRAINT fk_attempt_quiz
        FOREIGN KEY (quiz_id)
        REFERENCES quizzes(quiz_id),

    CONSTRAINT fk_attempt_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);
CREATE TABLE student_answers (
    answer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id NUMBER NOT NULL,
    question_id NUMBER NOT NULL,
    choice_id NUMBER,
    answer_text CLOB,
    is_correct NUMBER(1) DEFAULT 0 NOT NULL
        CHECK (is_correct IN (0,1)),

    CONSTRAINT fk_answer_attempt
        FOREIGN KEY (attempt_id)
        REFERENCES quiz_attempts(attempt_id),

    CONSTRAINT fk_answer_question
        FOREIGN KEY (question_id)
        REFERENCES questions(question_id),

    CONSTRAINT fk_answer_choice
        FOREIGN KEY (choice_id)
        REFERENCES choices(choice_id)
);
CREATE TABLE chapter_progress (
    progress_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    chapter_id NUMBER NOT NULL,
    status VARCHAR2(50) DEFAULT 'NOT_STARTED' NOT NULL,
    completion_date DATE,

    CONSTRAINT fk_progress_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id),

    CONSTRAINT fk_progress_chapter
        FOREIGN KEY (chapter_id)
        REFERENCES chapters(chapter_id)
);
COMMIT;