# Generated by Django 5.2.12 on 2026-04-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source_url', models.URLField()),
                ('category', models.CharField(choices=[('java', 'Java'), ('algorithm', 'Algorithmique'), ('oop', 'POO'), ('logic', 'Logique'), ('general', 'Général')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
